before_commands:
  - 'composer install'
  
filter:
  exluded_paths:
    - vendor/
    - bin/
    
tools:
  php_mess_detector: true
  php_analyzer: true
  php_code_sniffer: true
  php_code_coverage: true
  php_cpd: true
  php_loc: true
  php_pdepend: true
  external_code_coverage: true  
